name: aegregore:latest

on:
  push:
    branches: [ "builds" ]
  pull_request:
    branches: [ "builds" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file base.dockerfile --tag aegregore/workspace:latest
